server:
  port: 83

spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  service-1: http://nacos-provider-payment

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true